import pandas as pd

"""
equity_curve_from_trades() : function to build an equity curve at BTC chandles using trade logs and price series
    Assumptions for the deployed strategies:
      - BUY opens a position (qty > 0)
      - SELL_* closes it (qty > 0)
    
@params : price_df - input pandas dataframe with ['timestamp','close'] at the strategy's timestamp
          trades - list of dictionaries <K,V> generated by a given strategy (with 'date','action', etc.)
    
@returns: output pandad dataframe with the -> ['timestamp','equity','cash','btc']

"""

def equity_curve_from_trades(trades, price_df, initial_budget):

    df = price_df[['timestamp','close']].copy().sort_values('timestamp')
    df['equity'] = float(initial_budget)
    df['cash'] = float(initial_budget)
    df['btc'] = 0.0

    # index trades by timestamp for quick lookups
    tdf = pd.DataFrame(trades)
    tdf = tdf.sort_values('date') if not tdf.empty else tdf

    open_qty = 0.0
    cash = float(initial_budget)

    t_idx = 0
    t_len = 0 if tdf.empty else len(tdf)

    for i, row in df.iterrows():
        ts = row['timestamp']
        price = float(row['close'])

        # apply all trades that happen at or before this timestamp
        while t_idx < t_len and tdf.iloc[t_idx]['date'] <= ts:
            tr = tdf.iloc[t_idx]
            action = tr['action']
            if action == 'BUY':
                qty = float(tr['qty'])
                cost = qty * price
                if cost <= cash and qty > 0:
                    cash -= cost
                    open_qty += qty
            elif action.startswith('SELL'):
                qty = float(tr['qty'])
                if qty > 0 and open_qty >= qty:
                    proceeds = qty * price
                    cash += proceeds
                    open_qty -= qty
            elif action == 'STOP_TRADING':
                # no position change here; strategy loop already halted.
                pass
            t_idx += 1

        equity = cash + open_qty * price
        df.at[i, 'cash'] = cash
        df.at[i, 'btc'] = open_qty
        df.at[i, 'equity'] = equity

    return df[['timestamp','equity','cash','btc']]

"""
merge_equity_curves() - function to the merge the equity curves for display in the dash app 
@params : curves - a <K,V> dict of dataframes for each strategy like this -> {'DCA': df1, 'ATR': df2, 'Swing': df3}
@return : an output dataframe with timestamp + one equity column per strategy.    
"""

def merge_equity_curves(curves: dict):

    out = None
    for name, cdf in curves.items():
        c = cdf[['timestamp','equity']].rename(columns={'equity': name})
        out = c if out is None else out.merge(c, on='timestamp', how='outer')
    return out.sort_values('timestamp').reset_index(drop=True)
